In [36]:
import pandas as pd
import numpy as np
import nltk
import re
import warnings
warnings.filterwarnings('ignore')

In [3]:
### reading the dataset
df =  pd.read_csv('amazon.csv')

In [4]:
df.head()

Text  label
0  This is  the best apps acording to a bunch of ...      1
1  This is a pretty good version of the game for ...      1
2  this is a really . there are a bunch of levels...      1
3  This is a silly game and can be frustrating, b...      1
4  This is a terrific game on any pad. Hrs of fun...      1

In [6]:
### data cleaning and preprocessing
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from nltk.stem import WordNetLemmatizer

ps = PorterStemmer()
wordnet=WordNetLemmatizer()

corpus = []
for i in range(0, len(df)):
    review = re.sub('[^a-zA-Z]', ' ', df['Text'][i])
    review = review.lower()
    review = review.split()
    review = [wordnet.lemmatize(word) for word in review if not word in stopwords.words('english')]
    #review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [16]:
# Creating the Bag of Words model
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000)
X = cv.fit_transform(corpus).toarray()

In [15]:
# Creating the TF-IDF model
from sklearn.feature_extraction.text import TfidfVectorizer
tfv = TfidfVectorizer(max_features=5000)
X1 = tfv.fit_transform(corpus).toarray()

In [17]:
### Specifying our target variable y
y = df['label']

In [57]:
# Train Test Split_with_BOW
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0, stratify=y)

In [62]:
# Training model using Naive bayes classifier_BOW
from sklearn.naive_bayes import MultinomialNB
spam_detect_model = MultinomialNB(alpha=1)
spam_detect_model.fit(X_train, y_train)

y_pred=spam_detect_model.predict(X_test)
y_pred_train = spam_detect_model.predict(X_train)

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
print("Test Data Results: ") 
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print("***"*20)
print("Training Data Results:")
print(accuracy_score(y_train,y_pred_train))
print(classification_report(y_train,y_pred_train))
print(confusion_matrix(y_train,y_pred_train))

Test Data Results: 
0.8849769953990798
              precision    recall  f1-score   support

           0       0.74      0.80      0.77      1192
           1       0.93      0.91      0.92      3807

    accuracy                           0.88      4999
   macro avg       0.84      0.85      0.85      4999
weighted avg       0.89      0.88      0.89      4999

[[ 948  244]
 [ 331 3476]]
************************************************************
Training Data Results:
0.9106487964259519
              precision    recall  f1-score   support

           0       0.80      0.84      0.82      3574
           1       0.95      0.93      0.94     11423

    accuracy                           0.91     14997
   macro avg       0.87      0.89      0.88     14997
weighted avg       0.91      0.91      0.91     14997

[[ 3005   569]
 [  771 10652]]


In [63]:
# Train Test Split_with_tfidf
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X1, y, test_size = 0.25, random_state = 0, stratify=y)

In [64]:
# Training model using Naive bayes classifier_tfidf
from sklearn.naive_bayes import MultinomialNB
spam_detect_model = MultinomialNB(alpha=1)
spam_detect_model.fit(X_train, y_train)

y_pred=spam_detect_model.predict(X_test)
y_pred_train = spam_detect_model.predict(X_train)

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
print("Test Data Results: ") 
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print("***"*20)
print("Training Data Results:")
print(accuracy_score(y_train,y_pred_train))
print(classification_report(y_train,y_pred_train))
print(confusion_matrix(y_train,y_pred_train))

Test Data Results: 
0.8505701140228046
              precision    recall  f1-score   support

           0       0.90      0.42      0.57      1192
           1       0.84      0.99      0.91      3807

    accuracy                           0.85      4999
   macro avg       0.87      0.70      0.74      4999
weighted avg       0.86      0.85      0.83      4999

[[ 499  693]
 [  54 3753]]
************************************************************
Training Data Results:
0.8764419550576782
              precision    recall  f1-score   support

           0       0.94      0.51      0.66      3574
           1       0.87      0.99      0.92     11423

    accuracy                           0.88     14997
   macro avg       0.90      0.75      0.79     14997
weighted avg       0.88      0.88      0.86     14997

[[ 1834  1740]
 [  113 11310]]
